In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC

In [2]:
df = pd.read_excel('Raffles.xlsx')

In [3]:
df

Date  Raffle Clubs Diamond Heart Leaf
0     2019-11-11   40592     Q      10     Q    8
1     2019-11-11   40591    10       Q     9    K
2     2019-11-11   40590     J       K     9    9
3     2019-11-11   40589     Q       K     K    7
4     2019-11-11   40588    10       A     A    J
...          ...     ...   ...     ...   ...  ...
37588 1994-03-14       5    10       9     9    7
37589 1994-03-13       4     J       J     A    9
37590 1994-03-11       3     7       A     9    Q
37591 1994-03-10       2     9       K     K    Q
37592 1994-03-09       1     A       9     A    9

[37593 rows x 6 columns]

In [4]:
Y = df['Raffle']

In [5]:
X = df[['Clubs','Diamond','Heart','Leaf']]

In [6]:
X

Clubs Diamond Heart Leaf
0         Q      10     Q    8
1        10       Q     9    K
2         J       K     9    9
3         Q       K     K    7
4        10       A     A    J
...     ...     ...   ...  ...
37588    10       9     9    7
37589     J       J     A    9
37590     7       A     9    Q
37591     9       K     K    Q
37592     A       9     A    9

[37593 rows x 4 columns]

In [7]:
cols = X.columns

In [8]:
enc = LabelEncoder()

In [9]:
encoded_data = dict()
for c in cols:
    encoded_data[c] = enc.fit_transform(X[c].astype(str))

In [10]:
encoded_data = pd.DataFrame(encoded_data)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(encoded_data,Y,test_size = 0.2,random_state = 9,shuffle = False)

In [19]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((30074, 4), (7519, 4), (30074,), (7519,))

In [20]:
model = SVR(C=1.0, epsilon=0.2)

In [21]:
model.fit(X_train,y_train)

SVR(epsilon=0.2)

In [22]:
y_predict = model.predict(X_test)

In [23]:
for i,c in enumerate(cols):
    print(X_test.iloc[0,i])

0
3
2
2


In [25]:
print(f'prediction on one value is ==> {int(y_predict[0])}' )

prediction on one value is ==> 25547


In [28]:
len(X_train)

30074

In [36]:
for c in cols:
    print(enc.inverse_transform(X_test[c])[0])

10
9
8
8


In [38]:
for c in cols:
    print(df[c].unique())

['Q' 10 'J' 'K' 7 8 9 'A']
[10 'Q' 'K' 'A' 8 9 'J' 7]
['Q' 9 'K' 'A' 10 7 'J' 8]
[8 'K' 9 7 'J' 'Q' 'A' 10]


In [26]:
df.head()

Date  Raffle Clubs Diamond Heart Leaf
0 2019-11-11   40592     Q      10     Q    8
1 2019-11-11   40591    10       Q     9    K
2 2019-11-11   40590     J       K     9    9
3 2019-11-11   40589     Q       K     K    7
4 2019-11-11   40588    10       A     A    J

In [29]:
df[df['Raffle'] == 25547]

Date  Raffle Clubs Diamond Heart Leaf
15045 2012-05-13   25547     9       9     8    K

In [33]:
df = pd.read_excel('Raffles.xlsx')

In [35]:
df

Date  Raffle Clubs Diamond Heart Leaf
0     2019-11-11   40592     Q      10     Q    8
1     2019-11-11   40591    10       Q     9    K
2     2019-11-11   40590     J       K     9    9
3     2019-11-11   40589     Q       K     K    7
4     2019-11-11   40588    10       A     A    J
...          ...     ...   ...     ...   ...  ...
37588 1994-03-14       5    10       9     9    7
37589 1994-03-13       4     J       J     A    9
37590 1994-03-11       3     7       A     9    Q
37591 1994-03-10       2     9       K     K    Q
37592 1994-03-09       1     A       9     A    9

[37593 rows x 6 columns]

In [111]:
X_train, X_test, y_train, y_test = train_test_split(df['Date'],df['Clubs'])

In [112]:
enc = LabelEncoder()
encoded = enc.fit_transform(y_train.astype(str))

In [113]:
encoded

array([3, 6, 7, ..., 1, 3, 6])

In [70]:
model = SVC()

In [71]:
model.fit(np.resize(X_train,(28194,1)),encoded)

SVC()

12124   2013-10-28
20964   2009-04-22
11177   2014-04-13
29313   2004-07-17
29776   2004-03-25
           ...    
16021   2011-11-20
12889   2013-06-10
10909   2014-06-05
8285    2015-09-22
25840   2006-07-19
Name: Date, Length: 28194, dtype: datetime64[ns]

In [81]:
np.resize(X_train,(28194,1))[0]

array(['2013-10-28T00:00:00.000000000'], dtype='datetime64[ns]')

In [83]:
np.resize(X_test,(9399,1))[0]

array(['2006-01-25T00:00:00.000000000'], dtype='datetime64[ns]')

In [85]:
model.predict([np.resize(X_test,(9399,1))[0]])

array([6])

In [109]:
X_train, X_test, y_train, y_test = train_test_split(df['Date'],df['Diamond'])
enc = LabelEncoder()
encoded = enc.fit_transform(y_train.astype(str))

In [89]:
diamond_model = SVC()

In [91]:
diamond_model.fit(np.resize(X_train,(28194,1)),encoded)

SVC()

In [92]:
diamond_model.predict([np.resize(X_test,(9399,1))[0]])

array([5])

In [106]:
X_train, X_test, y_train, y_test = train_test_split(df['Date'],df['Heart'])
heart = LabelEncoder()
encoded = heart.fit_transform(y_train.astype(str))

In [95]:
heart = SVC()

In [96]:
heart.fit(np.resize(X_train,(28194,1)),encoded)
heart.predict([np.resize(X_test,(9399,1))[0]])

array([0])

In [103]:
X_train, X_test, y_train, y_test = train_test_split(df['Date'],df['Leaf'])
leaf = LabelEncoder()
encoded = leaf.fit_transform(y_train.astype(str))


In [101]:
leaf = SVC()
leaf.fit(np.resize(X_train,(28194,1)),encoded)
leaf.predict([np.resize(X_test,(9399,1))[0]])

array([2])

In [105]:
print('leaf.inverse_transform([2]))

['8']


In [108]:
print(heart.inverse_transform([0]))

['10']


In [110]:
print(diamond.inverse_transform([5]))

['J']


In [114]:
print(clubs.inverse_transform([6]))

['K']


In [115]:
[np.resize(X_test,(9399,1))[0]]

[array(['2008-07-30T00:00:00.000000000'], dtype='datetime64[ns]')]

In [116]:
df[df['Date'] ==  '2008-07-30']

Date  Raffle Clubs Diamond Heart Leaf
22237 2008-07-30   18355     9       7     K    Q
22238 2008-07-30   18354     A      10     J    A
22239 2008-07-30   18353     J       9     J    K
22240 2008-07-30   18352     9       8     K    8
22241 2008-07-30   18351     A       J     9    9
22242 2008-07-30   18350     9       7     Q    J

In [232]:
print("input DAte ==> 2020-7-11 ")
enc = LabelEncoder()
encoded = enc.fit_transform(df['Clubs'].astype(str))
club = SVC()
X = []
for i in df['Date']:
    X.append(datetime.datetime.fromisoformat(str(k)).timestamp())
X = np.resize(np.array(X),(len(X),1))
club.fit(X,encoded)
_ = datetime.datetime.fromisoformat('2020-07-11 00:00:00').timestamp()
a = str(_)[:10].replace('-','')
a = float(a)
output = club.predict(np.array([[a]]))
print("for club ==> {}".format(enc.inverse_transform(output)))
enc = LabelEncoder()
encoded = enc.fit_transform(df['Diamond'].astype(str))
club = SVC()
club.fit(X,encoded)
_ = datetime.datetime.fromisoformat('2020-07-11 00:00:00').timestamp()
a = str(_)[:10].replace('-','')
a = float(a)
output = club.predict(np.array([[a]]))
print("for diamond ==> {}".format(enc.inverse_transform(output)))
enc = LabelEncoder()
encoded = enc.fit_transform(df['Heart'].astype(str))
club = SVC()
club.fit(X,encoded)
_ = datetime.datetime.fromisoformat('2020-07-11 00:00:00').timestamp()
a = str(_)[:10].replace('-','')
a = float(a)
output = club.predict(np.array([[a]]))
print("for heart ==> {}".format(enc.inverse_transform(output)))
enc = LabelEncoder()
encoded = enc.fit_transform(df['Leaf'].astype(str))
club = SVC()
club.fit(X,encoded)
_ = datetime.datetime.fromisoformat('2020-07-11 00:00:00').timestamp()
a = str(_)[:10].replace('-','')
a = float(a)
output = club.predict(np.array([[a]]))
print("for leaf ==> {}".format(enc.inverse_transform(output)))

input DAte ==> 2020-7-11 
for club ==> ['A']
for diamond ==> ['J']
for heart ==> ['7']
for leaf ==> ['A']


In [230]:
_ = datetime.datetime.fromisoformat('2019-11-11 00:00:00').timestamp()
a = str(_)[:10].replace('-','')
a = float(a)
output = club.predict(np.array([[a]]))
print("for club ==> {}".format(enc.inverse_transform(output)))

ValueError: Invalid isoformat string: '2020-7-11 00:00:00'

array([[1.5734592e+09]])

In [160]:
str(k) 
datetime.datetime.fromisoformat(str(k)).timestamp()

1573459200.0

In [171]:
a = str(k)[:10].replace('-','')

In [179]:
encoded

array([7, 0, 5, ..., 1, 3, 4])

In [214]:
type(X[0][0]

numpy.float64

In [217]:
type(float(a))

float

In [233]:
x1 = df['Raffle']

In [242]:
from xgboost import XGBClassifier

In [293]:
enc = LabelEncoder()
encoded = enc.fit_transform(df['Clubs'].astype(str))
club = XGBClassifier()
club.fit(np.resize(x1,(x1.shape[0],1)),encoded)
o = enc.inverse_transform(club.predict(np.array([[40593]])))
print(f"Clubs ==> {o}")
enc = LabelEncoder()
encoded = enc.fit_transform(df['Diamond'].astype(str))
diamond = XGBClassifier()
diamond.fit(np.resize(x1,(x1.shape[0],1)),encoded)
o = enc.inverse_transform(diamond.predict(np.array([[40593]])))
print(f"Diamond ==> {o}")
enc = LabelEncoder()
encoded = enc.fit_transform(df['Heart'].astype(str))
heart = XGBClassifier()
heart.fit(np.resize(x1,(x1.shape[0],1)),encoded)
o = enc.inverse_transform(heart.predict(np.array([[40593]])))
print(f"Heart ==> {o}")
enc = LabelEncoder()
encoded = enc.fit_transform(df['Leaf'].astype(str))
leaf = XGBClassifier()
leaf.fit(np.resize(x1,(x1.shape[0],1)),encoded)
o = enc.inverse_transform(leaf.predict(np.array([[40593]])))
print(f"Leaf ==> {o}")

Clubs ==> ['Q']
Diamond ==> ['K']
Heart ==> ['9']
Leaf ==> ['8']


In [258]:
X2 = pd.DataFrame({'xdate':np.reshape(X,(X.shape[0])),'raffle':x1.values})

In [292]:
xpd = pd.DataFrame({'xdate':[1594450800.0],'raffle':[40593]})
enc1 = LabelEncoder()
encoded = enc1.fit_transform(df['Clubs'].astype(str))
club = XGBClassifier()
club.fit(X2,encoded)
o = enc1.inverse_transform(club.predict(xpd))
print(f"Clubs ==> {o}")
enc2 = LabelEncoder()
encoded = enc2.fit_transform(df['Diamond'].astype(str))
diamond = XGBClassifier()
diamond.fit(X2,encoded)
o = enc2.inverse_transform(club.predict(xpd))
print(f"Diamond ==> {o}")
enc3 = LabelEncoder()
encoded = enc3.fit_transform(df['Heart'].astype(str))
heart = XGBClassifier()
heart.fit(X2,encoded)
o = enc3.inverse_transform(club.predict(xpd))
print(f"Heart ==> {o}")
enc4 = LabelEncoder()
encoded = enc4.fit_transform(df['Leaf'].astype(str))
leaf = XGBClassifier()
leaf.fit(X2,encoded)
o = enc4.inverse_transform(club.predict(xpd))
print(f"Leaf ==> {o}")

Clubs ==> ['Q']
Diamond ==> ['Q']
Heart ==> ['Q']
Leaf ==> ['Q']


In [294]:
leaf

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [276]:
xpd

xdata  raffle
0  1.573459e+09   40572

In [282]:
_ = datetime.datetime.fromisoformat('2020-07-11 00:00:00').timestamp()
a = str(_)[:10].replace('-','')
a = float(a)

In [283]:
a

1594450800.0